### PR TITLE
Engine/camera depth scale fix

### LINKED ISSUE #94: Far clipping plane distance reduces when camera zoom increases
When zoom = 1, sprites in scene stop being rendered at z = 100;
zoom = 2, at z = 51;
zoom = 3, at z = 34.

It seems that the far clipping plane distance gets divided by zoom value at some point.

### PR DESCRIPTION
**Pull request by UbiBelETF**
Fixes #94 
Please test.

### CODE REVIEW

File: source/dagger/core/input/inputs.cpp [hunk 1]
```diff
@@ -271,12 +271,13 @@ void InputSystem::Run()
 					}
 				}
 
-				for (auto& [key, value] : receiver_.values)
```
Comment (DPrivalov) [inline source/dagger/core/input/inputs.cpp:274]: hm... strange that this one is here

**Review by DPrivalov — APPROVED** [review]
